server:
  port: 9000
  address: 0.0.0.0

backend-server:
  address: 192.168.1.131
  port: 8080

nginx-server:
  address: 192.168.1.131
  port: 80

scheduler-server:
  address: 192.168.1.131
  port: 7000